name: sample_project
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  nb_utils: ^5.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  ## HOW TO ADD ASSETS
  # assets:
  #   - lib/core/assets/svg/map/bin-map-bad.svg
  ## HOME TO ADD FONTS
  # fonts:
  # - family: Oswald
  #   fonts:
  #     - asset: lib/core/assets/fonts/Oswald/Oswald-ExtraLight.ttf
  #       weight: 200
  #     - asset: lib/core/assets/fonts/Oswald/Oswald-Light.ttf
  #       weight: 300
  #     - asset: lib/core/assets/fonts/Oswald/Oswald-Regular.ttf
  #       weight: 400
  #     - asset: lib/core/assets/fonts/Oswald/Oswald-Medium.ttf
  #       weight: 500
  #     - asset: lib/core/assets/fonts/Oswald/Oswald-SemiBold.ttf
  #       weight: 600
  #     - asset: lib/core/assets/fonts/Oswald/Oswald-Bold.ttf
  #       weight: 700
